In [36]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression

In [37]:
df = pd.read_csv("../data/taxi_trip_pricing.csv")

df.head()

   Trip_Distance_km Time_of_Day  ... Trip_Duration_Minutes  Trip_Price
0             19.35     Morning  ...                 53.82     36.2624
1             47.59   Afternoon  ...                 40.57         NaN
2             36.87     Evening  ...                 37.27     52.9032
3             30.33     Evening  ...                116.81     36.4698
4               NaN     Evening  ...                 22.64     15.6180

[5 rows x 11 columns]

In [38]:
df["Trip_Price"].isnull().sum()

np.int64(49)

In [39]:
# Dropping Trip Price missing values as if we are not having output itself so how can we train the model on that particular row or for that particular features
df = df.dropna(subset=["Trip_Price"])

In [40]:
df["Trip_Price"].isnull().sum()

np.int64(0)

In [41]:
X = df.drop(columns=["Trip_Price"])
y = df["Trip_Price"]

In [42]:
X.head()

   Trip_Distance_km Time_of_Day  ... Per_Minute_Rate  Trip_Duration_Minutes
0             19.35     Morning  ...            0.32                  53.82
2             36.87     Evening  ...            0.15                  37.27
3             30.33     Evening  ...            0.15                 116.81
4               NaN     Evening  ...            0.32                  22.64
5              8.64   Afternoon  ...            0.48                  89.33

[5 rows x 10 columns]

In [43]:
y.head()

0    36.2624
2    52.9032
3    36.4698
4    15.6180
5    60.2028
Name: Trip_Price, dtype: float64

In [44]:
print("X shape: ", X.shape)
print("y shape: ", y.shape)

X shape:  (951, 10)
y shape:  (951,)

In [45]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [46]:
print("X_train: ", X_train.shape)
print("X_test: ", X_test.shape)

print("y_train: ", y_train.shape)
print("y_test: ", y_test.shape)

X_train:  (760, 10)
X_test:  (191, 10)
y_train:  (760,)
y_test:  (191,)

In [47]:
numerical_features = X_train.select_dtypes(include="number").columns.tolist()

numerical_features

['Trip_Distance_km',
 'Passenger_Count',
 'Base_Fare',
 'Per_Km_Rate',
 'Per_Minute_Rate',
 'Trip_Duration_Minutes']

In [48]:
categorical_features = X_train.select_dtypes(include="str").columns.tolist()

categorical_features

['Time_of_Day', 'Day_of_Week', 'Traffic_Conditions', 'Weather']

In [49]:
# We are using the median strategy for imputer to fill all the nan values because there are some outliers that can make out mean more or less so because of that we are using median
numerical_pipeline = Pipeline([
    ("inputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [50]:
# Here we are using mode/most frequent strategy for imputer as for categorical columns that is the only thing we can do here
# The handle_unknown="ignore" tells us that if in future the column have some another value so it will not throw an error instead it will ignore that row
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [51]:
# Here we are processing the numerical features with the numerical pipeline and the categorical features with the categorical piepeline
preprocessor = ColumnTransformer([
    ("num", numerical_pipeline, numerical_features),
    ("cat", categorical_pipeline, categorical_features)
])

In [52]:
# We use fit_transform on the train data because the fit learns the parameters from the data such as mean, std, etc.
X_train_processed = preprocessor.fit_transform(X_train)

In [53]:
# We use transform on the test data because we dont want out test data get the paramteres from the data such as mean, std, etc.
X_test_processed = preprocessor.transform(X_test)

In [54]:
# The number of features of X_train_processed has increased because of the one hot encoding we have used in four categorial features
print("Original X_train shape: ", X_train.shape)
print("Processed X_train shape: ", X_train_processed.shape)

Original X_train shape:  (760, 10)
Processed X_train shape:  (760, 18)

In [55]:
print("Original X_test shape: ", X_test.shape)
print("Processed X_test shape: ", X_test_processed.shape)

Original X_test shape:  (191, 10)
Processed X_test shape:  (191, 18)

In [57]:
model_pipeline = Pipeline([
    ("pre_processor", preprocessor),
    ("model", LinearRegression())
])

In [58]:
model_pipeline.fit(X_train, y_train)

Pipeline(steps=[('pre_processor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('inputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Trip_Distance_km',
                                                   'Passenger_Count',
                                                   'Base_Fare', 'Per_Km_Rate',
                                                   'Per_Minute_Rate',
                                                   'Trip_Duration_Minutes']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Time_of_Day', 'Day_of_Week',
                                                   'Traffic_Conditions',
                                                   'Weather'])])),
                ('model', LinearRegression())])

In [59]:
predictions = model_pipeline.predict(X_test)